image: node:latest

# Cache modules in between jobs
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

stages:
  - test
  - build
  - deploy

npm-install:
  stage: .pre
  script:
    - npm install

lint-job:
  stage: test
  script:
    - npm run lint

unit-test-job:
  stage: test
  script:
    - npm run test

build-job:
  stage: build
  script:
    - npm run rollup

deploy:
  stage: deploy
  only:
    - develop
  script:
    - npm publish
