image: node:16

stages:
  - test
  - build

npm-install:
  stage: .pre
  script:
    - npm install

cache:
  paths:
    - node_modules/

lint-and-test-job:
  stage: test
  script:
    - npm run test

build-job:
  stage: build
  script:
    - npm run rollup
