stages:
  - .pre
  - test
  - compile
  - build
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH # Only commit or merge


npm-install:
  stage: .pre
  tags:
    - "init"
  image: node:18-alpine
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm install
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull-push
    paths:
      - ".npm"


lint-job:
  stage: test
  tags:
    - "test"
  image: node:18-alpine
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run lint
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull
    paths:
      - ".npm"

unit-test-job:
  stage: test
  tags:
    - "test"
  image: node:18-alpine
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run test
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull
    paths:
      - ".npm"

build-job:
  stage: test
  tags:
    - "test"
  image: node:18-alpine
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run rollup
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull
    paths:
      - ".npm"
  artifacts:
    when: always
    paths:
      - "dist"


"Build Storybook":
  stage: compile
  environment: DEV
  image: node:18-alpine
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run build-storybook
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull
    paths:
      - ".npm"
  artifacts:
    when: always
    paths:
      - "storybook-static"
  only:
    - develop
    - /^devops\/.*$/


"Publish package":
  stage: deploy
  tags:
    - "deploy"
  image: node:18-alpine
  needs:
    - build-job
  script:
    - echo "@eslovensko:registry=https://gitlab.slovenskoit.sk/api/v4/projects/${CI_PROJECT_ID}/packages/npm/">.npmrc
    - echo "//gitlab.slovenskoit.sk/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - npm publish
  only:
    - develop

"Increment Build number":
  stage: build
  tags:
    - "init"
  environment: DEV
  image: "bash:5.1.8"
  before_script:
    - apk add curl jq
  script:
    - source ./ci/lib-build.sh
    - set -x # Activate debug.
    - increment_build_number
  only:
    - develop
    - /^devops\/.*$/

"Build Docker image":
  stage: build
  environment: DEV
  image: "docker:stable"
  needs:
    - "Increment Build number"
    - "Build Storybook"
  before_script:
    - apk add --update bash curl jq
  script:
    - bash -xc "source ./ci/lib-build.sh; docker_build_image"
    - bash -xc "source ./ci/lib-build.sh; docker_push_image"
  only:
    - develop
    - /^devops\/.*$/


"Deploy":
  stage: deploy
  tags:
    - "deploy"
  environment: DEV
  image: "kroniak/ssh-client:3.11"
  variables:
    SSH_CONNECT: "deploy@library.dev.idsk.skit.zone"
  before_script:
    - apk add --update bash curl jq
  script:
    - source ./ci/lib-deploy.sh
    - set -x # Activate debug.
    - deploy_docker_login
    - deploy_docker_compose
  only:
    - develop
    - /^devops\/.*$/
