version: "3.9"

networks:
  traefik_net:
    name: "traefik_net"
    external: true


services:
  esvk_web_lib_idsk_react:
    container_name: "esvk_web_lib_idsk_react"
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    restart: "unless-stopped"
    networks:
      - "traefik_net"
    logging:
      driver: "loki"
      options:
        max-size: "5m"
        max-file: "2"
        loki-url: "http://loki.${CI_ENVIRONMENT_NAME_LOWER}.svm.skit.zone/loki/api/v1/push"
        loki-timeout: "3s"
        loki-retries: "5"
    environment:
      TZ: "Europe/Bratislava"
    labels:
      traefik.enable: "true"
      traefik.http.services.web.loadbalancer.server.port: "80"
      traefik.http.services.web.loadbalancer.server.scheme: "http"

      traefik.http.routers.web.service: "web"
      traefik.http.routers.web.rule: "Host(`reactlib.${CI_ENVIRONMENT_NAME_LOWER}.idsk.skit.zone`)"
      traefik.http.routers.web.entrypoints: "web"
